NAME = megaphone

FLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++

all: $(NAME)
$(NAME): megaphone.cpp
		@$(CC) $(FLAGS) megaphone.cpp -o $(NAME)
clean : 
	rm $(NAME)
fclean :
	rm $(NAME)
re :clean all